body:
  - type: markdown
    attributes:
      value: |
        **Note**: This category is intended for sharing ideas related to Vercel CLI or Runtimes. 

        Please visit the [Vercel Community](https://vercel.community) to share ideas for other Vercel tools and features.
  - type: textarea
    attributes:
      label: Idea
    validations:
      required: true
